import { useState } from "react"
import { List, ListItem, ListItemText} from "@mui/material"
// import { styled, Button, SvgIcon } from "@mui/joy"

const FileList = () => {
    const [files, setFiles] = useState([])

    const handleChange = (event) => {
        const inputFiles = event.target.files

        const newArray = Array.from(inputFiles).filter(newFile =>
            !files.some(existingFiles => existingFiles.name === newFile.name)
        )

        event.target.value = null

        setFiles(prevFiles => [...prevFiles , ...newArray])
    }

    const sendFiles = () => {
        const formData = new FormData()

        files.map((file, index) => {
            formData.append(`${ file.type }-${ index }`, file)
        })

        fetch("http://127.0.0.1:7878/send-file", {
            // This request doesn't include "content type" header, because the content type needs to be
            // generated by the browser, so the browser can include the multipart boundary and content type dynamically.
            // If the header is added the backend will return a response with "Bad Request" status.
            // Makes sense considering that Postman uses "multipart/form-data; boundary=<calculated when request is sent>" header.
            method: "POST",
            body: formData
        })
        .then(response => {
            if (response.ok) {
                console.log("File sent successfully")
            }

            else console.log("Sending the file failed")
        })
        .catch(error => console.log("Error occured while sending the file", error))
    }

    return (
        <>
        <div className="section-container">
            <div className="notification-container no-files">
                <h3>No files to transfer</h3>
                <input type="file" name="filepicker" multiple onChange={ handleChange } />
                <div>
                    <button onClick={ sendFiles }>Send</button>
                </div>
                { files.length > 0 && (
                    <div className="list-container">
                        <CustomList fileList={ files } setFiles={ setFiles } />
                    </div>
                ) }
            </div>
        </div>
        </>
    )
}

interface ListProps {
    fileList: Array<object>,
    setFiles: Function
}

const CustomList = (props: ListProps) => {

    const formatBytes = (bytes: number, decimals = 2): string => {
        if (bytes === 0) return '0 Bytes'

        const k = 1024
        const dm = decimals < 0 ? 0 : decimals
        const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']

        const i = Math.floor(Math.log(bytes) / Math.log(k))

        return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + " " + sizes[i]
    }

    const removeFile = (fileName: string) => {
        const newList = props.fileList.filter(file => file.name !== fileName)
        props.setFiles(newList)
    }

    const itemList = props.fileList.map((item, index) => (
        <ListItem disablePadding key={ index }>
            <button onClick={ () => removeFile(item.name) }>Remove</button>
            <ListItemText primary={ `${ item.name } ${ item.type } ${ formatBytes(item.size) }` } />
        </ListItem>
    ))

    return (
        <List>
            { itemList }
        </List>
    )
}

export default FileList
